### ISSUE TITLE
Reformatting Movement and Shodan catalog pages

### ISSUE THREAD

**Issue by jkapusci** [sul-cidr/noh#321]
These pages should have a title within the "filter" interface rather than have h2 title that takes too much space.

**Comment by gworthey** [comment]
Paraphrasing Jarek:
The problem is that the big centered and underlined title “Catalog of Kata”: http://61d24de9db.cidr.stanford.edu/movement/ 
takes a lot of vertical space. 

One option (others are possible) would be to include the title above the “Filter by format” navigation bar.

There are two challenges with this option: 1. How to enable the little triangle indicator beneath the "Catalog of Kata" thumbnail that indicates the active page, and 2. Putting the title here might exacerbate the problem of the non-scrolling left-navigation bar (which is dealt with in #323).

**Comment by broadwell** [comment]
There's also some annoying jumping/auto-scroll behavior that happens when the filters towards the bottom of the list are selected or deselected. For example, open http://61d24de9db.cidr.stanford.edu/movement/, scroll down, and click on the checkbox next to "Open" to select or deselect it. Holding off on filing it as a bug because it may be affected by the reformatting for this issue or what is done to address #322.
