### ISSUE TITLE
<br> inside the “collapsible” class does not work

### ISSUE THREAD

**Issue by jkapusci** [sul-cidr/noh#326]

**Comment by broadwell** [comment]
This bug occurs because the "narrative" HTML data is loaded in as a string and divided into "chunks" (which become the Level 1 "INTRO", "ACT I", etc. tab sections) by splitting the string on artificially inserted `<br/>` tags. A `<br>` (or `<br/>`) tag used anywhere else in the narrative breaks this scheme.
One solution is just to split the "narrative" strings on the `<section>` tags instead, but a likely more robust fix is to treat the "narrative" string as HTML and then create the "chunks" by parsing the `<section>` elements. This is what PR #346 proposes.

**Comment by simonwiles** [comment]
Closed by #346.
