### ISSUE TITLE
Broken L2 links to catalog of shōdan for non-shōdan sections

### ISSUE THREAD

**Issue by broadwell** [sul-cidr/noh#592]
The following L2 pages have links in the top right of the left-hand info panel entitled "In Catalog of Shōdan" but the links don't actually lead to pages in the Catalog, probably because they're not real shōdan sections. It's likely best just to remove the links, as is done for other non-shōdan sections like `/musicians-walk-in/`:
- `/hashitomi/song/`
- `/kokaji/dialogue/`
- `/kokaji/monologue/`

**Comment by inefable** [comment]
It also happens with `/hashitomi/mid-exit/`. The problem is that the data for distinguishing shodans from non-shodans is the same that the one setting this link. If we remove the data from the spreadsheet to remove the link, then these blocks will be in white. 

Tomorrow I have a meeting with Jarek and Francois, so I can ask them if these shodans should point to a specific page in the catalog.

**Comment by broadwell** [comment]
All of the links now lead to content.
